### ISSUE TITLE
Speaker embeddings and params. 

### ISSUE THREAD

**Issue by DwaraknathT** [Edresson/SC-GlowTTS#1]
Hi, 

Thank you for providing demo code! It works really well on the given test samples. 
However, when I try to use a sample from a custom dataset, the speaker embedding are not able to capture the features of the speaker. If I try to generate speech from a female voice reference, the generated voice is male. 

I calculated the cosine similarities between reference and custom dataset speaker embeddings and here is what I found 
Male - Female : 0.216
Male - Female custom : 0.028
Male - Male custom : -0.015
Female - Female custom: -0.02 

Can you please let me know if there are any specific preprocessing steps that I to follow ? the reference audio clips are Mono channel, 16KHz and clips of 10 seconds. 

Thanks again for your work! Really appreciate it!

**Comment by Edresson** [comment]
Apologies for the delay. I didn't see the notification for that issue. See the discussion [here](https://github.com/coqui-ai/TTS/discussions/459)
