### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by The0nix** [Edresson/SC-GlowTTS#2]
Hello! I am trying to train SC-GlowTTS models and can not figure out the proper way to do this. I tried launching `train_glow_tts.py` script from [coqui-ai/TTS](https://github.com/coqui-ai/TTS) with config and commit hash from colab notebooks, but this generates errors and I am not sure this is a correct way to do it. I also tried using [configs from coqui](https://github.com/coqui-ai/TTS/releases/tag/v0.0.13) with the latest version but this does not work either. Could you please explain, what are the intended steps to reproduce your experiments? :)

**Comment by Edresson** [comment]
Hello,
Since the implementation of the model, the Coqui repository has undergone some restructuring. For you to train SC-GlowTTS-Trans use config.json and speakers.json present [here](https://github.com/coqui-ai/TTS/releases/download/v0.0.12/tts_models--en--vctk--sc-glowtts-transformer.zip).

**Comment by The0nix** [comment]
Now it points to "not found" page. :(

**Comment by Edresson** [comment]
@The0nix  Try again.
