### ISSUE TITLE
Wav inference doesn't work on Colab

### ISSUE THREAD

**Issue by jlmarrugom** [Edresson/SC-GlowTTS#3]
Hi, I've been studying this paper, and most of your work, I find it very insightful and promising. The problem I have is that when I try to run the Google Colab Example: _SC-GlowTTS-Trans+HiFi-GAN-FT_ I get an error in the row: 

`_, wav = tts(model, TEXT, C, USE_CUDA, ap, use_griffin_lim, None, speaker_embedding=speaker_embedding)`

The error is: **Error in dlopen for library libnvrtc.so.10.2and libnvrtc-08c4863f.so.10.2**. I've been trying to solve it for a while, but haven't found an answer. It maybe is related to the Cuda drivers on Colab. 
Do you know how to solve it?

Thanks for everything.

**Comment by Edresson** [comment]
Hi, I tested here and everything works fine. Please check if your Colab Notebook has a GPU, maybe It is the problem.
